# Generated by Django 5.2.8 on 2025-12-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_options_pedido_entregado_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='mesa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
