# Generated by Django 5.2.8 on 2025-12-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedido_mesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mesa',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='plato',
            field=models.CharField(max_length=60),
        ),
    ]
